{% set version = "1.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-scattermore
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/scattermore_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/scattermore/scattermore_{{ version }}.tar.gz
  sha256: a71d5d1ae06bc6b7d9a446293e3c12a5ce970754c24a0cc6f31ad0ea52cbaf91

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'           # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-scales                     # [build_platform != target_platform]
    - r-ggplot2                    # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-ggplot2
    - r-scales
  run:
    - r-base
    - {{ native }}gcc-libs           # [win]
    - {{ native }}libwinpthread-git  # [win]
    - r-ggplot2
    - r-scales

test:
  commands:
    - $R -e "library('scattermore')"           # [not win]
    - "\"%R%\" -e \"library('scattermore')\""  # [win]

about:
  home: https://github.com/exaexa/scattermore
  doc_url: https://exaexa.github.io/scattermore/
  license: GPL-3.0-or-later
  summary: C-based conversion of large scatterplot data to rasters. Speeds up plotting of data with millions of points.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
